description: "Develop components like plugins and themes for your website with wordpress"
name: stack-wordpress
display-name: "Stack Wordpress"
picture: stack.png
category: Full Stack
compatibility: ["Php7.4", "Docker", "Mysql5.7", "Wordpress" ]
technologies: [ "Docker", "Php"]

about: docs/about.md
use-cases:
  - title: "Default - Wordpress WebSite"
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml