description: "Develop components like plugins and themes for your website with wordpress"
name: stack-wordpress
display-name: "Stack Wordpress"
picture: stack.png

category: "Backend"

compatibility:
  - AWS

technologies:
  - Docker

about: docs/about.md
use-cases:
  - title: "Default - Wordpress WebSite"
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml